//! Bulk operations for CurrencyExchange entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCurrencyExchangeDto;
use crate::application::service::CurrencyExchangeService;
use crate::domain::entity::CurrencyExchange;

/// Bulk operation handler for CurrencyExchange entities.
///
/// Wraps `CurrencyExchangeService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CurrencyExchangeBulkService = GenericBulkService<CurrencyExchange, CreateCurrencyExchangeDto, CurrencyExchangeService>;

// <<< CUSTOM
// END CUSTOM
