//! Bulk operations for Currency entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCurrencyDto;
use crate::application::service::CurrencyService;
use crate::domain::entity::Currency;

/// Bulk operation handler for Currency entities.
///
/// Wraps `CurrencyService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CurrencyBulkService = GenericBulkService<Currency, CreateCurrencyDto, CurrencyService>;

// <<< CUSTOM
// END CUSTOM
