//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod currency_bulk;
pub mod currency_exchange_bulk;
pub mod incoterm_bulk;
pub mod terms_and_conditions_bulk;
pub mod territory_bulk;

pub use currency_bulk::CurrencyBulkService;
pub use currency_exchange_bulk::CurrencyExchangeBulkService;
pub use incoterm_bulk::IncotermBulkService;
pub use terms_and_conditions_bulk::TermsAndConditionsBulkService;
pub use territory_bulk::TerritoryBulkService;

// <<< CUSTOM
// END CUSTOM
