//! Bulk operations for TermsAndConditions entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTermsAndConditionsDto;
use crate::application::service::TermsAndConditionsService;
use crate::domain::entity::TermsAndConditions;

/// Bulk operation handler for TermsAndConditions entities.
///
/// Wraps `TermsAndConditionsService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TermsAndConditionsBulkService = GenericBulkService<TermsAndConditions, CreateTermsAndConditionsDto, TermsAndConditionsService>;

// <<< CUSTOM
// END CUSTOM
