//! Bulk operations for Territory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTerritoryDto;
use crate::application::service::TerritoryService;
use crate::domain::entity::Territory;

/// Bulk operation handler for Territory entities.
///
/// Wraps `TerritoryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TerritoryBulkService = GenericBulkService<Territory, CreateTerritoryDto, TerritoryService>;

// <<< CUSTOM
// END CUSTOM
