//! Corporate Module Routes
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides route composition with dual pattern support:
//! - Stateless routes: `create_stateless_routes()` -> `Router<()>`
//! - Stateful routes: `create_stateful_routes()` -> `Router<AppState>`

use axum::Router;
use std::sync::Arc;

// Import handlers
use crate::presentation::http::{
    create_currency_routes,
    create_currency_read_routes,
    create_currency_exchange_routes,
    create_currency_exchange_read_routes,
    create_incoterm_routes,
    create_incoterm_read_routes,
    create_terms_and_conditions_routes,
    create_terms_and_conditions_read_routes,
    create_territory_routes,
    create_territory_read_routes
};

// Import AppState for stateful routes
use crate::handlers::AppState;

// ============================================================
// PATTERN 1: STATELESS ROUTES
// ============================================================

/// Create stateless routes for the Corporate module.
///
/// These routes don't require shared state and are simpler to use.
/// Use this when you only need standard CRUD operations.
///
/// # Example
///
/// ```ignore
/// let module = CorporateModule::builder().with_database(pool).build()?;
/// let routes = create_stateless_routes(&module);
/// let app = Router::new().merge(routes);
/// ```
pub fn create_stateless_routes(module: &crate::CorporateModule) -> Router<()> {
    Router::new()
        .merge(create_currency_routes(module.currency_service.clone()))
        // Rate table is READ-only in the default composer — a rate's value is its
        // no-overlap + directional + effective-dated invariant, enforced only in
        // FxService::upsert_rate. Generic write CRUD would bypass it (the DB
        // EXCLUDE/CHECK backstops money-correctness, but the friendly errors and
        // the validated write throat live at POST /fx/rates). Use all_crud_routes()
        // for the trusted/admin full-write surface.
        .merge(create_currency_exchange_read_routes(module.currency_exchange_service.clone()))
        .merge(create_incoterm_routes(module.incoterm_service.clone()))
        .merge(create_terms_and_conditions_routes(module.terms_and_conditions_service.clone()))
        .merge(create_territory_routes(module.territory_service.clone()))
}

/// Read-only routes for the Corporate module — every entity mounted READ-ONLY (the guarded base).
///
/// The generic `create_stateless_routes` exposes full mutable CRUD with no domain
/// validation; this exposes only reads, so generic mutation can't bypass a write
/// service's invariants. Extend it: `create_readonly_corporate_routes(m).merge(my_validated_writes)`.
pub fn create_readonly_corporate_routes(module: &crate::CorporateModule) -> Router<()> {
    Router::new()
        .merge(create_currency_read_routes(module.currency_service.clone()))
        .merge(create_currency_exchange_read_routes(module.currency_exchange_service.clone()))
        .merge(create_incoterm_read_routes(module.incoterm_service.clone()))
        .merge(create_terms_and_conditions_read_routes(module.terms_and_conditions_service.clone()))
        .merge(create_territory_read_routes(module.territory_service.clone()))
}

/// Get all routes (stateless) for the Corporate module.
///
/// This is a convenience function that wraps routes with API versioning.
pub fn get_routes(module: &crate::CorporateModule) -> Router<()> {
    Router::new()
        .nest("/api/v1", create_stateless_routes(module))
}

// ============================================================
// PATTERN 2: STATEFUL ROUTES (WITH APPSTATE)
// ============================================================

/// Create stateful routes for the Corporate module.
///
/// These routes require AppState and support custom handlers
/// that need access to services via dependency injection.
///
/// # Example
///
/// ```ignore
/// let module = CorporateModule::builder().with_database(pool).build()?;
/// let state = AppState::from_module(&module);
/// let routes = create_stateful_routes();
/// let app = Router::new().merge(routes).with_state(state);
/// ```
pub fn create_stateful_routes() -> Router<AppState> {
    Router::new()
        // Add custom handlers here that need AppState
        // .route("/custom", get(custom_handler))
}

/// Create combined routes (stateless CRUD + stateful custom handlers).
///
/// This merges both stateless CRUD routes and stateful custom routes.
pub fn create_combined_routes(module: &crate::CorporateModule) -> Router<AppState> {
    // First create stateless routes
    let crud_routes: Router<()> = create_stateless_routes(module);

    // Convert to stateful by adding state requirement
    // Note: The CRUD routes don't actually use the state,
    // but this allows them to be merged with stateful routes.
    let crud_routes_stateful: Router<AppState> = crud_routes.with_state(()).into();

    // Merge with stateful routes
    Router::new()
        .merge(crud_routes_stateful)
        .merge(create_stateful_routes())
        .merge(create_fx_routes())
}

/// Get all routes (stateful) for the Corporate module.
///
/// This is a convenience function that wraps routes with API versioning.
pub fn get_routes_with_state(module: &crate::CorporateModule) -> Router<AppState> {
    Router::new()
        .nest("/api/v1", create_combined_routes(module))
}

// ============================================================
// CUSTOM HANDLERS
// ============================================================

// <<< CUSTOM HANDLERS START >>>
// Add custom route handlers here
use axum::routing::post;
use crate::handlers::custom::{register_fx_rate, convert_fx};

/// Validated FX endpoints — the sanctioned write throat for rates and the
/// conversion endpoint. `POST /fx/rates` goes through `FxService::upsert_rate`
/// (overlap + positivity + direction invariants), NOT generic CRUD; `POST
/// /fx/convert` exposes the effective-dated conversion. Mount alongside the
/// read-only stateless routes via `create_combined_routes`.
pub fn create_fx_routes() -> Router<AppState> {
    Router::new()
        .route("/fx/rates", post(register_fx_rate))
        .route("/fx/convert", post(convert_fx))
}
// <<< CUSTOM HANDLERS END >>>
