//! CurrencyExchange DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::CurrencyExchange;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CurrencyExchange
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCurrencyExchangeDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "from_currency")]
    pub from_currency: String,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "to_currency")]
    pub to_currency: String,
    pub rate: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "effective_from")]
    pub effective_from: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "effective_to")]
    pub effective_to: Option<NaiveDate>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CurrencyExchange
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCurrencyExchangeDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "from_currency")]
    pub from_currency: String,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "to_currency")]
    pub to_currency: String,
    pub rate: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "effective_from")]
    pub effective_from: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "effective_to")]
    pub effective_to: Option<NaiveDate>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CurrencyExchange
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCurrencyExchangeDto {
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "from_currency")]
    pub from_currency: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "to_currency")]
    pub to_currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rate: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "effective_from")]
    pub effective_from: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "effective_to")]
    pub effective_to: Option<NaiveDate>,
}

impl PatchCurrencyExchangeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.from_currency.is_some() || self.to_currency.is_some() || self.rate.is_some() || self.effective_from.is_some() || self.effective_to.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CurrencyExchange entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CurrencyExchangeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub from_currency: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub to_currency: String,
    pub rate: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub effective_from: NaiveDate,
    pub effective_to: Option<NaiveDate>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CurrencyExchange entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CurrencyExchangeListResponseDto {
    /// List of items
    pub items: Vec<CurrencyExchangeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CurrencyExchangeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CurrencyExchangeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CurrencyExchangeSummaryDto {
    pub id: Uuid,
    pub company_id: Option<Uuid>,
    pub from_currency: String,
    pub to_currency: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CurrencyExchange> for CurrencyExchangeResponseDto {
    fn from(entity: CurrencyExchange) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            from_currency: entity.from_currency,
            to_currency: entity.to_currency,
            rate: entity.rate,
            effective_from: entity.effective_from,
            effective_to: entity.effective_to,
            metadata: entity.metadata,
        }
    }
}

impl From<CurrencyExchange> for CurrencyExchangeSummaryDto {
    fn from(entity: CurrencyExchange) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            from_currency: entity.from_currency,
            to_currency: entity.to_currency,
            created_at,
        }
    }
}

impl From<CreateCurrencyExchangeDto> for CurrencyExchange {
    fn from(dto: CreateCurrencyExchangeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            from_currency: dto.from_currency,
            to_currency: dto.to_currency,
            rate: dto.rate,
            effective_from: dto.effective_from,
            effective_to: dto.effective_to,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CurrencyExchange> for CurrencyExchangeResponseDto {
    fn from(entity: &CurrencyExchange) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            from_currency: entity.from_currency.clone(),
            to_currency: entity.to_currency.clone(),
            rate: entity.rate.clone(),
            effective_from: entity.effective_from.clone(),
            effective_to: entity.effective_to.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCurrencyExchangeDto> for CurrencyExchange {
    fn from_create_dto(dto: CreateCurrencyExchangeDto) -> backbone_core::ServiceResult<Self> {
        Ok(CurrencyExchange::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCurrencyExchangeDto> for CurrencyExchange {
    fn apply_update(mut self, dto: UpdateCurrencyExchangeDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.from_currency = dto.from_currency;
        self.to_currency = dto.to_currency;
        self.rate = dto.rate;
        self.effective_from = dto.effective_from;
        self.effective_to = dto.effective_to;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CurrencyExchange here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
