//! Currency DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Currency;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Currency
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCurrencyDto {
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "iso_code")]
    pub iso_code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 8)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "decimal_places")]
    pub decimal_places: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Currency
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCurrencyDto {
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "iso_code")]
    pub iso_code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 8)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "decimal_places")]
    pub decimal_places: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Currency
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCurrencyDto {
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "iso_code")]
    pub iso_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 8)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "decimal_places")]
    pub decimal_places: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchCurrencyDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.iso_code.is_some() || self.name.is_some() || self.symbol.is_some() || self.decimal_places.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Currency entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CurrencyResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub iso_code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub symbol: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub decimal_places: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Currency entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CurrencyListResponseDto {
    /// List of items
    pub items: Vec<CurrencyResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CurrencyListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CurrencyResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CurrencySummaryDto {
    pub id: Uuid,
    pub iso_code: String,
    pub name: String,
    pub symbol: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Currency> for CurrencyResponseDto {
    fn from(entity: Currency) -> Self {
        Self {
            id: entity.id,
            iso_code: entity.iso_code,
            name: entity.name,
            symbol: entity.symbol,
            decimal_places: entity.decimal_places,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<Currency> for CurrencySummaryDto {
    fn from(entity: Currency) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            iso_code: entity.iso_code,
            name: entity.name,
            symbol: entity.symbol,
            created_at,
        }
    }
}

impl From<CreateCurrencyDto> for Currency {
    fn from(dto: CreateCurrencyDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            iso_code: dto.iso_code,
            name: dto.name,
            symbol: dto.symbol,
            decimal_places: dto.decimal_places,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Currency> for CurrencyResponseDto {
    fn from(entity: &Currency) -> Self {
        Self {
            id: entity.id.clone(),
            iso_code: entity.iso_code.clone(),
            name: entity.name.clone(),
            symbol: entity.symbol.clone(),
            decimal_places: entity.decimal_places.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCurrencyDto> for Currency {
    fn from_create_dto(dto: CreateCurrencyDto) -> backbone_core::ServiceResult<Self> {
        Ok(Currency::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCurrencyDto> for Currency {
    fn apply_update(mut self, dto: UpdateCurrencyDto) -> backbone_core::ServiceResult<Self> {
        self.iso_code = dto.iso_code;
        self.name = dto.name;
        self.symbol = dto.symbol;
        self.decimal_places = dto.decimal_places;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Currency here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
