//! TermsAndConditions DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::TermsAndConditions;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TermsAndConditions
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTermsAndConditionsDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "validation", validate(length(max = 8000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TermsAndConditions
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTermsAndConditionsDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "validation", validate(length(max = 8000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TermsAndConditions
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTermsAndConditionsDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 8000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchTermsAndConditionsDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.code.is_some() || self.title.is_some() || self.body.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TermsAndConditions entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TermsAndConditionsResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TermsAndConditions entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TermsAndConditionsListResponseDto {
    /// List of items
    pub items: Vec<TermsAndConditionsResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TermsAndConditionsListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TermsAndConditionsResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TermsAndConditionsSummaryDto {
    pub id: Uuid,
    pub code: String,
    pub title: String,
    pub body: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TermsAndConditions> for TermsAndConditionsResponseDto {
    fn from(entity: TermsAndConditions) -> Self {
        Self {
            id: entity.id,
            code: entity.code,
            title: entity.title,
            body: entity.body,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<TermsAndConditions> for TermsAndConditionsSummaryDto {
    fn from(entity: TermsAndConditions) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            code: entity.code,
            title: entity.title,
            body: entity.body,
            created_at,
        }
    }
}

impl From<CreateTermsAndConditionsDto> for TermsAndConditions {
    fn from(dto: CreateTermsAndConditionsDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            code: dto.code,
            title: dto.title,
            body: dto.body,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TermsAndConditions> for TermsAndConditionsResponseDto {
    fn from(entity: &TermsAndConditions) -> Self {
        Self {
            id: entity.id.clone(),
            code: entity.code.clone(),
            title: entity.title.clone(),
            body: entity.body.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTermsAndConditionsDto> for TermsAndConditions {
    fn from_create_dto(dto: CreateTermsAndConditionsDto) -> backbone_core::ServiceResult<Self> {
        Ok(TermsAndConditions::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTermsAndConditionsDto> for TermsAndConditions {
    fn apply_update(mut self, dto: UpdateTermsAndConditionsDto) -> backbone_core::ServiceResult<Self> {
        self.code = dto.code;
        self.title = dto.title;
        self.body = dto.body;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TermsAndConditions here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
