//! Domain policy for Currency aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Currency;

/// Domain policy for Currency — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Currency>` in the `// <<< CUSTOM` zone.
pub type CurrencyDomainPolicy = PermitAllPolicy<Currency>;

// <<< CUSTOM
// END CUSTOM
