//! Domain policy for Incoterm aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Incoterm;

/// Domain policy for Incoterm — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Incoterm>` in the `// <<< CUSTOM` zone.
pub type IncotermDomainPolicy = PermitAllPolicy<Incoterm>;

// <<< CUSTOM
// END CUSTOM
