//! Domain policy for Territory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Territory;

/// Domain policy for Territory — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Territory>` in the `// <<< CUSTOM` zone.
pub type TerritoryDomainPolicy = PermitAllPolicy<Territory>;

// <<< CUSTOM
// END CUSTOM
