//! Application service for CurrencyExchange entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `currency_exchange_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCurrencyExchangeDto, UpdateCurrencyExchangeDto};
use crate::domain::entity::CurrencyExchange;
use crate::infrastructure::persistence::CurrencyExchangeRepository;

/// Application service for CurrencyExchange entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `currency_exchange_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CurrencyExchangeServiceCustom {
///     inner: Arc<CurrencyExchangeService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CurrencyExchangeService = GenericCrudService<
    CurrencyExchange,
    CreateCurrencyExchangeDto,
    UpdateCurrencyExchangeDto,
    CurrencyExchangeRepository,
>;

// <<< CUSTOM
// END CUSTOM
