//! Application service for Currency entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `currency_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCurrencyDto, UpdateCurrencyDto};
use crate::domain::entity::Currency;
use crate::infrastructure::persistence::CurrencyRepository;

/// Application service for Currency entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `currency_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CurrencyServiceCustom {
///     inner: Arc<CurrencyService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CurrencyService = GenericCrudService<
    Currency,
    CreateCurrencyDto,
    UpdateCurrencyDto,
    CurrencyRepository,
>;

// <<< CUSTOM
// END CUSTOM
