//! Application service for Incoterm entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `incoterm_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateIncotermDto, UpdateIncotermDto};
use crate::domain::entity::Incoterm;
use crate::infrastructure::persistence::IncotermRepository;

/// Application service for Incoterm entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `incoterm_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct IncotermServiceCustom {
///     inner: Arc<IncotermService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type IncotermService = GenericCrudService<
    Incoterm,
    CreateIncotermDto,
    UpdateIncotermDto,
    IncotermRepository,
>;

// <<< CUSTOM
// END CUSTOM
