//! Application service for TermsAndConditions entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `terms_and_conditions_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTermsAndConditionsDto, UpdateTermsAndConditionsDto};
use crate::domain::entity::TermsAndConditions;
use crate::infrastructure::persistence::TermsAndConditionsRepository;

/// Application service for TermsAndConditions entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `terms_and_conditions_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TermsAndConditionsServiceCustom {
///     inner: Arc<TermsAndConditionsService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TermsAndConditionsService = GenericCrudService<
    TermsAndConditions,
    CreateTermsAndConditionsDto,
    UpdateTermsAndConditionsDto,
    TermsAndConditionsRepository,
>;

// <<< CUSTOM
// END CUSTOM
