-- CurrencyExchange Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the corporate.currency_exchanges table.
-- Customize this file to add your initial data.

-- INSERT INTO corporate.currency_exchanges (
--     id,
--     company_id,
--     from_currency,
--     to_currency,
--     rate,
--     effective_from,
--     effective_to,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO corporate.currency_exchanges (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

