-- Enum types for corporate module
-- Generated by metaphor-schema

-- Create currency_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'currency_status') THEN
        CREATE TYPE currency_status AS ENUM ('active', 'inactive');
    END IF;
END
$$;

-- Create rate_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'rate_type') THEN
        CREATE TYPE rate_type AS ENUM ('spot', 'avg_period', 'period_end');
    END IF;
END
$$;

