-- Migration: Create terms_and_conditions table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS corporate;

CREATE TABLE IF NOT EXISTS corporate.terms_and_conditions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    code TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_terms_and_conditions_code ON corporate.terms_and_conditions (code) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_terms_and_conditions_metadata_gin ON corporate.terms_and_conditions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_terms_and_conditions_metadata_deleted_at ON corporate.terms_and_conditions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_terms_and_conditions_metadata_created_at ON corporate.terms_and_conditions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_terms_and_conditions_metadata_updated_at ON corporate.terms_and_conditions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION corporate.terms_and_conditions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS terms_and_conditions_insert_audit ON corporate.terms_and_conditions;
CREATE TRIGGER terms_and_conditions_insert_audit BEFORE INSERT ON corporate.terms_and_conditions
    FOR EACH ROW EXECUTE FUNCTION corporate.terms_and_conditions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS terms_and_conditions_update_audit ON corporate.terms_and_conditions;
CREATE TRIGGER terms_and_conditions_update_audit BEFORE UPDATE ON corporate.terms_and_conditions
    FOR EACH ROW EXECUTE FUNCTION corporate.terms_and_conditions_audit_timestamp();
