-- Migration: Create currency_exchanges table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS corporate;

CREATE TABLE IF NOT EXISTS corporate.currency_exchanges (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID,
    from_currency TEXT NOT NULL,
    to_currency TEXT NOT NULL,
    rate NUMERIC NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_currency_exchanges_from_currency_to_currency_effective_from ON corporate.currency_exchanges (from_currency, to_currency, effective_from);

CREATE INDEX IF NOT EXISTS idx_currency_exchanges_company_id ON corporate.currency_exchanges (company_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_currency_exchanges_metadata_gin ON corporate.currency_exchanges USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_currency_exchanges_metadata_deleted_at ON corporate.currency_exchanges ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_currency_exchanges_metadata_created_at ON corporate.currency_exchanges ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_currency_exchanges_metadata_updated_at ON corporate.currency_exchanges ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION corporate.currency_exchanges_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS currency_exchanges_insert_audit ON corporate.currency_exchanges;
CREATE TRIGGER currency_exchanges_insert_audit BEFORE INSERT ON corporate.currency_exchanges
    FOR EACH ROW EXECUTE FUNCTION corporate.currency_exchanges_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS currency_exchanges_update_audit ON corporate.currency_exchanges;
CREATE TRIGGER currency_exchanges_update_audit BEFORE UPDATE ON corporate.currency_exchanges
    FOR EACH ROW EXECUTE FUNCTION corporate.currency_exchanges_audit_timestamp();
