-- Audit Triggers Migration for corporate module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Currency (corporate.currencies)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION corporate.currencies_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS currencies_insert_audit ON corporate.currencies;
CREATE TRIGGER currencies_insert_audit BEFORE INSERT ON corporate.currencies
    FOR EACH ROW EXECUTE FUNCTION corporate.currencies_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS currencies_update_audit ON corporate.currencies;
CREATE TRIGGER currencies_update_audit BEFORE UPDATE ON corporate.currencies
    FOR EACH ROW EXECUTE FUNCTION corporate.currencies_audit_timestamp();

-- ==============================================================================
-- Table: CurrencyExchange (corporate.currency_exchanges)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION corporate.currency_exchanges_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS currency_exchanges_insert_audit ON corporate.currency_exchanges;
CREATE TRIGGER currency_exchanges_insert_audit BEFORE INSERT ON corporate.currency_exchanges
    FOR EACH ROW EXECUTE FUNCTION corporate.currency_exchanges_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS currency_exchanges_update_audit ON corporate.currency_exchanges;
CREATE TRIGGER currency_exchanges_update_audit BEFORE UPDATE ON corporate.currency_exchanges
    FOR EACH ROW EXECUTE FUNCTION corporate.currency_exchanges_audit_timestamp();

-- ==============================================================================
-- Table: Incoterm (corporate.incoterms)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION corporate.incoterms_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS incoterms_insert_audit ON corporate.incoterms;
CREATE TRIGGER incoterms_insert_audit BEFORE INSERT ON corporate.incoterms
    FOR EACH ROW EXECUTE FUNCTION corporate.incoterms_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS incoterms_update_audit ON corporate.incoterms;
CREATE TRIGGER incoterms_update_audit BEFORE UPDATE ON corporate.incoterms
    FOR EACH ROW EXECUTE FUNCTION corporate.incoterms_audit_timestamp();

-- ==============================================================================
-- Table: TermsAndConditions (corporate.terms_and_conditions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION corporate.terms_and_conditions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS terms_and_conditions_insert_audit ON corporate.terms_and_conditions;
CREATE TRIGGER terms_and_conditions_insert_audit BEFORE INSERT ON corporate.terms_and_conditions
    FOR EACH ROW EXECUTE FUNCTION corporate.terms_and_conditions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS terms_and_conditions_update_audit ON corporate.terms_and_conditions;
CREATE TRIGGER terms_and_conditions_update_audit BEFORE UPDATE ON corporate.terms_and_conditions
    FOR EACH ROW EXECUTE FUNCTION corporate.terms_and_conditions_audit_timestamp();

-- ==============================================================================
-- Table: Territory (corporate.territories)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION corporate.territories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS territories_insert_audit ON corporate.territories;
CREATE TRIGGER territories_insert_audit BEFORE INSERT ON corporate.territories
    FOR EACH ROW EXECUTE FUNCTION corporate.territories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS territories_update_audit ON corporate.territories;
CREATE TRIGGER territories_update_audit BEFORE UPDATE ON corporate.territories
    FOR EACH ROW EXECUTE FUNCTION corporate.territories_audit_timestamp();

