-- Migration: Create territories table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS corporate;

CREATE TABLE IF NOT EXISTS corporate.territories (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    parent_id UUID,
    is_group BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_territories_code ON corporate.territories (code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_territories_parent_id ON corporate.territories (parent_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_territories_metadata_gin ON corporate.territories USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_territories_metadata_deleted_at ON corporate.territories ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_territories_metadata_created_at ON corporate.territories ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_territories_metadata_updated_at ON corporate.territories ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION corporate.territories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS territories_insert_audit ON corporate.territories;
CREATE TRIGGER territories_insert_audit BEFORE INSERT ON corporate.territories
    FOR EACH ROW EXECUTE FUNCTION corporate.territories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS territories_update_audit ON corporate.territories;
CREATE TRIGGER territories_update_audit BEFORE UPDATE ON corporate.territories
    FOR EACH ROW EXECUTE FUNCTION corporate.territories_audit_timestamp();
