//! Domain events for CurrencyExchange entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CurrencyExchange;

/// Domain events for CurrencyExchange — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CurrencyExchange>)` variant.
pub type CurrencyExchangeEvent = CrudEvent<CurrencyExchange>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CurrencyExchange events.
pub type CurrencyExchangeEventPublisher = Arc<dyn CrudEventPublisher<CurrencyExchange> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCurrencyExchangeEventPublisher = NoOpCrudEventPublisher<CurrencyExchange>;
