//! Event handler trait for CurrencyExchange events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::CurrencyExchangeEvent;
use backbone_messaging::EventHandler;

/// Event handler for CurrencyExchange events.
/// Implement this trait to react to CurrencyExchange lifecycle events.
pub trait CurrencyExchangeEventHandler: EventHandler<CurrencyExchangeEvent> {}
