//! Event handler trait for Currency events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::CurrencyEvent;
use backbone_messaging::EventHandler;

/// Event handler for Currency events.
/// Implement this trait to react to Currency lifecycle events.
pub trait CurrencyEventHandler: EventHandler<CurrencyEvent> {}
