//! Event handler trait for CurrencyExchange events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CurrencyExchangeEvent;

/// Event handler for CurrencyExchange events.
/// Implement this trait to react to CurrencyExchange lifecycle events.
pub trait CurrencyExchangeEventHandler: EventHandler<CurrencyExchangeEvent> {}
