//! Domain events for Incoterm entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Incoterm;

/// Domain events for Incoterm — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Incoterm>)` variant.
pub type IncotermEvent = CrudEvent<Incoterm>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Incoterm events.
pub type IncotermEventPublisher = Arc<dyn CrudEventPublisher<Incoterm> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopIncotermEventPublisher = NoOpCrudEventPublisher<Incoterm>;
