//! Event handler trait for Incoterm events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::IncotermEvent;

/// Event handler for Incoterm events.
/// Implement this trait to react to Incoterm lifecycle events.
pub trait IncotermEventHandler: EventHandler<IncotermEvent> {}
