//! Event handler trait for TermsAndConditions events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TermsAndConditionsEvent;

/// Event handler for TermsAndConditions events.
/// Implement this trait to react to TermsAndConditions lifecycle events.
pub trait TermsAndConditionsEventHandler: EventHandler<TermsAndConditionsEvent> {}
