//! Domain events for TermsAndConditions entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::TermsAndConditions;

/// Domain events for TermsAndConditions — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TermsAndConditions>)` variant.
pub type TermsAndConditionsEvent = CrudEvent<TermsAndConditions>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TermsAndConditions events.
pub type TermsAndConditionsEventPublisher = Arc<dyn CrudEventPublisher<TermsAndConditions> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTermsAndConditionsEventPublisher = NoOpCrudEventPublisher<TermsAndConditions>;
