//! Event handler trait for Territory events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::TerritoryEvent;
use backbone_messaging::EventHandler;

/// Event handler for Territory events.
/// Implement this trait to react to Territory lifecycle events.
pub trait TerritoryEventHandler: EventHandler<TerritoryEvent> {}
