//! Domain events for Territory entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Territory;

/// Domain events for Territory — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Territory>)` variant.
pub type TerritoryEvent = CrudEvent<Territory>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Territory events.
pub type TerritoryEventPublisher = Arc<dyn CrudEventPublisher<Territory> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTerritoryEventPublisher = NoOpCrudEventPublisher<Territory>;
