//! Event subscriber type aliases for Corporate module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::CurrencyEvent;
use crate::domain::event::CurrencyExchangeEvent;
use crate::domain::event::IncotermEvent;
use crate::domain::event::TermsAndConditionsEvent;
use crate::domain::event::TerritoryEvent;

/// Subscriber for Currency events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type CurrencyEventSubscriber = GenericEventSubscriber<CurrencyEvent>;

/// Subscriber for CurrencyExchange events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type CurrencyExchangeEventSubscriber = GenericEventSubscriber<CurrencyExchangeEvent>;

/// Subscriber for Incoterm events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type IncotermEventSubscriber = GenericEventSubscriber<IncotermEvent>;

/// Subscriber for TermsAndConditions events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type TermsAndConditionsEventSubscriber = GenericEventSubscriber<TermsAndConditionsEvent>;

/// Subscriber for Territory events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type TerritoryEventSubscriber = GenericEventSubscriber<TerritoryEvent>;

// <<< CUSTOM
// END CUSTOM
