//! Corporate Event Subscriptions
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Cross-module event subscriptions. Each entity subscriber is a type alias
//! over `GenericEventSubscriber` from backbone-messaging.

pub mod handlers;
pub mod registry;

pub use handlers::*;
pub use registry::SubscriptionRegistry;

pub use handlers::CurrencyEventSubscriber;
pub use handlers::CurrencyExchangeEventSubscriber;
pub use handlers::IncotermEventSubscriber;
pub use handlers::TermsAndConditionsEventSubscriber;
pub use handlers::TerritoryEventSubscriber;
