//! Incoterm seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Incoterm data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// INCOTERM SEEDER
// ============================================================================

/// Seeder for incoterm
pub struct SeedIncotermSeeder;

impl SeedIncotermSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedIncotermSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedIncotermSeeder {
    fn name(&self) -> &'static str {
        "SeedIncotermSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if corporate.incoterms table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM corporate.incoterms")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/incoterm_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM corporate.incoterms")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

