//! TermsAndConditions seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial TermsAndConditions data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TERMSANDCONDITIONS SEEDER
// ============================================================================

/// Seeder for terms_and_conditions
pub struct SeedTermsAndConditionsSeeder;

impl SeedTermsAndConditionsSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTermsAndConditionsSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTermsAndConditionsSeeder {
    fn name(&self) -> &'static str {
        "SeedTermsAndConditionsSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if corporate.terms_and_conditions table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM corporate.terms_and_conditions")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/terms_and_conditions_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM corporate.terms_and_conditions")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

