//! Territory seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Territory data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TERRITORY SEEDER
// ============================================================================

/// Seeder for territory
pub struct SeedTerritorySeeder;

impl SeedTerritorySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTerritorySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTerritorySeeder {
    fn name(&self) -> &'static str {
        "SeedTerritorySeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if corporate.territories table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM corporate.territories")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/territory_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM corporate.territories")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

