//! Repository trait for CurrencyExchange aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CurrencyExchange aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::CurrencyExchange;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CurrencyExchangePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CurrencyExchangePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CurrencyExchangePaginatedResult {
    pub data: Vec<CurrencyExchange>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CurrencyExchangeFilter {
    pub company_id: Option<Uuid>,
    pub from_currency: Option<String>,
    pub to_currency: Option<String>,
}

impl CurrencyExchangeFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.from_currency.is_some() || self.to_currency.is_some()
    }
}

/// Repository trait for CurrencyExchange aggregate
///
/// This trait defines the persistence contract for CurrencyExchange entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CurrencyExchangeRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new currency_exchange entity
    async fn save(&self, entity: &CurrencyExchange) -> Result<CurrencyExchange>;

    /// Find currency_exchange by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CurrencyExchange>>;

    /// Find all currency_exchange entities
    async fn find_all(&self) -> Result<Vec<CurrencyExchange>>;

    /// Update currency_exchange by ID
    async fn update(&self, id: &str, entity: &CurrencyExchange) -> Result<Option<CurrencyExchange>>;

    /// Delete currency_exchange by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List currency_exchange with pagination
    async fn list(&self, params: CurrencyExchangePaginationParams) -> Result<CurrencyExchangePaginatedResult>;

    /// List currency_exchange with pagination and filters
    async fn list_with_filters(&self, params: CurrencyExchangePaginationParams, filters: CurrencyExchangeFilter) -> Result<CurrencyExchangePaginatedResult>;

    /// Count all currency_exchange entities
    async fn count(&self) -> Result<u64>;

    /// Count currency_exchange entities matching filters
    async fn count_with_filters(&self, filters: CurrencyExchangeFilter) -> Result<u64>;

    /// Check if currency_exchange exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete currency_exchange by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted currency_exchange by ID
    async fn restore(&self, id: &str) -> Result<Option<CurrencyExchange>>;

    /// List soft-deleted currency_exchange entities
    async fn list_deleted(&self, params: CurrencyExchangePaginationParams) -> Result<CurrencyExchangePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save currency_exchange entities
    async fn bulk_save(&self, entities: &[CurrencyExchange]) -> Result<Vec<CurrencyExchange>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
