//! Repository trait for Incoterm aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Incoterm aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::Incoterm;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct IncotermPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl IncotermPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct IncotermPaginatedResult {
    pub data: Vec<Incoterm>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct IncotermFilter {
    pub code: Option<String>,
    pub name: Option<String>,
    pub is_active: Option<bool>,
}

impl IncotermFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.code.is_some() || self.name.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for Incoterm aggregate
///
/// This trait defines the persistence contract for Incoterm entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait IncotermRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new incoterm entity
    async fn save(&self, entity: &Incoterm) -> Result<Incoterm>;

    /// Find incoterm by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Incoterm>>;

    /// Find all incoterm entities
    async fn find_all(&self) -> Result<Vec<Incoterm>>;

    /// Update incoterm by ID
    async fn update(&self, id: &str, entity: &Incoterm) -> Result<Option<Incoterm>>;

    /// Delete incoterm by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List incoterm with pagination
    async fn list(&self, params: IncotermPaginationParams) -> Result<IncotermPaginatedResult>;

    /// List incoterm with pagination and filters
    async fn list_with_filters(&self, params: IncotermPaginationParams, filters: IncotermFilter) -> Result<IncotermPaginatedResult>;

    /// Count all incoterm entities
    async fn count(&self) -> Result<u64>;

    /// Count incoterm entities matching filters
    async fn count_with_filters(&self, filters: IncotermFilter) -> Result<u64>;

    /// Check if incoterm exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete incoterm by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted incoterm by ID
    async fn restore(&self, id: &str) -> Result<Option<Incoterm>>;

    /// List soft-deleted incoterm entities
    async fn list_deleted(&self, params: IncotermPaginationParams) -> Result<IncotermPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save incoterm entities
    async fn bulk_save(&self, entities: &[Incoterm]) -> Result<Vec<Incoterm>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
