//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.

pub mod currency_exchange_repository;
pub mod currency_repository;
pub mod incoterm_repository;
pub mod terms_and_conditions_repository;
pub mod territory_repository;

// Re-exports
pub use currency_exchange_repository::{
    CurrencyExchangeFilter, CurrencyExchangePaginatedResult, CurrencyExchangePaginationParams,
    CurrencyExchangeRepository,
};
pub use currency_repository::{
    CurrencyFilter, CurrencyPaginatedResult, CurrencyPaginationParams, CurrencyRepository,
};
pub use incoterm_repository::{
    IncotermFilter, IncotermPaginatedResult, IncotermPaginationParams, IncotermRepository,
};
pub use terms_and_conditions_repository::{
    TermsAndConditionsFilter, TermsAndConditionsPaginatedResult,
    TermsAndConditionsPaginationParams, TermsAndConditionsRepository,
};
pub use territory_repository::{
    TerritoryFilter, TerritoryPaginatedResult, TerritoryPaginationParams, TerritoryRepository,
};
