//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod currency_repository;
pub mod currency_exchange_repository;
pub mod incoterm_repository;
pub mod terms_and_conditions_repository;
pub mod territory_repository;

// Re-exports
pub use currency_repository::{
    CurrencyRepository,
    CurrencyPaginationParams,
    CurrencyPaginatedResult,
    CurrencyFilter,
};
pub use currency_exchange_repository::{
    CurrencyExchangeRepository,
    CurrencyExchangePaginationParams,
    CurrencyExchangePaginatedResult,
    CurrencyExchangeFilter,
};
pub use incoterm_repository::{
    IncotermRepository,
    IncotermPaginationParams,
    IncotermPaginatedResult,
    IncotermFilter,
};
pub use terms_and_conditions_repository::{
    TermsAndConditionsRepository,
    TermsAndConditionsPaginationParams,
    TermsAndConditionsPaginatedResult,
    TermsAndConditionsFilter,
};
pub use territory_repository::{
    TerritoryRepository,
    TerritoryPaginationParams,
    TerritoryPaginatedResult,
    TerritoryFilter,
};
