//! Repository trait for TermsAndConditions aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TermsAndConditions aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::TermsAndConditions;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TermsAndConditionsPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TermsAndConditionsPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TermsAndConditionsPaginatedResult {
    pub data: Vec<TermsAndConditions>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TermsAndConditionsFilter {
    pub code: Option<String>,
    pub title: Option<String>,
    pub body: Option<String>,
    pub is_active: Option<bool>,
}

impl TermsAndConditionsFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.code.is_some() || self.title.is_some() || self.body.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for TermsAndConditions aggregate
///
/// This trait defines the persistence contract for TermsAndConditions entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TermsAndConditionsRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new terms_and_conditions entity
    async fn save(&self, entity: &TermsAndConditions) -> Result<TermsAndConditions>;

    /// Find terms_and_conditions by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TermsAndConditions>>;

    /// Find all terms_and_conditions entities
    async fn find_all(&self) -> Result<Vec<TermsAndConditions>>;

    /// Update terms_and_conditions by ID
    async fn update(&self, id: &str, entity: &TermsAndConditions) -> Result<Option<TermsAndConditions>>;

    /// Delete terms_and_conditions by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List terms_and_conditions with pagination
    async fn list(&self, params: TermsAndConditionsPaginationParams) -> Result<TermsAndConditionsPaginatedResult>;

    /// List terms_and_conditions with pagination and filters
    async fn list_with_filters(&self, params: TermsAndConditionsPaginationParams, filters: TermsAndConditionsFilter) -> Result<TermsAndConditionsPaginatedResult>;

    /// Count all terms_and_conditions entities
    async fn count(&self) -> Result<u64>;

    /// Count terms_and_conditions entities matching filters
    async fn count_with_filters(&self, filters: TermsAndConditionsFilter) -> Result<u64>;

    /// Check if terms_and_conditions exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete terms_and_conditions by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted terms_and_conditions by ID
    async fn restore(&self, id: &str) -> Result<Option<TermsAndConditions>>;

    /// List soft-deleted terms_and_conditions entities
    async fn list_deleted(&self, params: TermsAndConditionsPaginationParams) -> Result<TermsAndConditionsPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save terms_and_conditions entities
    async fn bulk_save(&self, entities: &[TermsAndConditions]) -> Result<Vec<TermsAndConditions>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
