//! Repository for Currency entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Currency, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Currency;

/// Table name for Currency entities
pub const TABLE_NAME: &str = "corporate.currencies";

/// Repository for Currency entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CurrencyRepository(
    backbone_orm::GenericCrudRepository<Currency, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CurrencyRepository {
    type Target = backbone_orm::GenericCrudRepository<Currency, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CurrencyRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CurrencyRepository, Currency, soft_delete);
