//! Repository for Currency entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom method
//! below holds the FX engine's decimal-places read (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Currency, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgConnection, PgPool};

use crate::domain::entity::Currency;

/// Table name for Currency entities
pub const TABLE_NAME: &str = "corporate.currencies";

/// Repository for Currency entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CurrencyRepository(
    backbone_orm::GenericCrudRepository<Currency, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CurrencyRepository {
    type Target = backbone_orm::GenericCrudRepository<Currency, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl CurrencyRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// FX decimal-precision read. Lives here (not in the service) per the module's 4-layer rule.
impl CurrencyRepository {
    /// The quote currency's minor-unit precision (IDR=0, USD=2). Read REGARDLESS of soft-delete
    /// state, so a historical document still reproduces its booked number after the quote currency
    /// is retired (ADR-001 Decision 1: history is never re-translated). `None` only for a
    /// never-registered code, so the caller errors rather than guessing a precision. Runs on the
    /// caller's tx; `corporate.currencies` is NOT company-fenced.
    pub async fn decimal_places_tx(
        &self,
        conn: &mut PgConnection,
        iso: &str,
    ) -> Result<Option<i32>, sqlx::Error> {
        sqlx::query_scalar("SELECT decimal_places FROM corporate.currencies WHERE iso_code=$1")
            .bind(iso)
            .fetch_optional(conn)
            .await
    }
}

backbone_core::impl_crud_repository!(CurrencyRepository, Currency, soft_delete);
