//! Repository for CurrencyExchange entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CurrencyExchange, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::CurrencyExchange;

/// Table name for CurrencyExchange entities
pub const TABLE_NAME: &str = "corporate.currency_exchanges";

/// Repository for CurrencyExchange entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CurrencyExchangeRepository(
    backbone_orm::GenericCrudRepository<CurrencyExchange, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CurrencyExchangeRepository {
    type Target = backbone_orm::GenericCrudRepository<CurrencyExchange, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CurrencyExchangeRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CurrencyExchangeRepository, CurrencyExchange, soft_delete);
