//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod currency_repository;
mod currency_exchange_repository;
mod incoterm_repository;
mod terms_and_conditions_repository;
mod territory_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use currency_repository::CurrencyRepository;
pub use currency_exchange_repository::CurrencyExchangeRepository;
pub use incoterm_repository::IncotermRepository;
pub use terms_and_conditions_repository::TermsAndConditionsRepository;
pub use territory_repository::TerritoryRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
