//! Repository for TermsAndConditions entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TermsAndConditions, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::TermsAndConditions;

/// Table name for TermsAndConditions entities
pub const TABLE_NAME: &str = "corporate.terms_and_conditions";

/// Repository for TermsAndConditions entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TermsAndConditionsRepository(
    backbone_orm::GenericCrudRepository<TermsAndConditions, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TermsAndConditionsRepository {
    type Target = backbone_orm::GenericCrudRepository<TermsAndConditions, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TermsAndConditionsRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TermsAndConditionsRepository, TermsAndConditions, soft_delete);
