//! Repository for Territory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Territory, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Territory;

/// Table name for Territory entities
pub const TABLE_NAME: &str = "corporate.territories";

/// Repository for Territory entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TerritoryRepository(
    backbone_orm::GenericCrudRepository<Territory, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TerritoryRepository {
    type Target = backbone_orm::GenericCrudRepository<Territory, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TerritoryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TerritoryRepository, Territory, soft_delete);
