//! Validator for Currency entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Currency>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Currency;

/// Validator type alias for Currency entities.
pub type CurrencyValidator = EntityValidator<Currency>;

/// Build a validator for Currency with all schema-defined field rules.
pub fn currency_validator() -> CurrencyValidator {
    EntityValidator::new()
        .rule(RequiredString::new("iso_code", |e: &Currency| &e.iso_code))
        .rule(RequiredString::new("name", |e: &Currency| &e.name))
        .rule(OptionalNotBlank::new("symbol", |e: &Currency| e.symbol.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
