//! Validator for CurrencyExchange entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CurrencyExchange>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::CurrencyExchange;

/// Validator type alias for CurrencyExchange entities.
pub type CurrencyExchangeValidator = EntityValidator<CurrencyExchange>;

/// Build a validator for CurrencyExchange with all schema-defined field rules.
pub fn currency_exchange_validator() -> CurrencyExchangeValidator {
    EntityValidator::new()
        .rule(RequiredString::new("from_currency", |e: &CurrencyExchange| &e.from_currency))
        .rule(RequiredString::new("to_currency", |e: &CurrencyExchange| &e.to_currency))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
