//! Validator for Incoterm entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Incoterm>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::Incoterm;

/// Validator type alias for Incoterm entities.
pub type IncotermValidator = EntityValidator<Incoterm>;

/// Build a validator for Incoterm with all schema-defined field rules.
pub fn incoterm_validator() -> IncotermValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &Incoterm| &e.code))
        .rule(RequiredString::new("name", |e: &Incoterm| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
