//! Validator for Territory entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Territory>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use crate::domain::entity::Territory;
use backbone_core::RequiredString;
use backbone_core::{EntityValidator, ValidationError, ValidationErrors};

/// Validator type alias for Territory entities.
pub type TerritoryValidator = EntityValidator<Territory>;

/// Build a validator for Territory with all schema-defined field rules.
pub fn territory_validator() -> TerritoryValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &Territory| &e.code))
        .rule(RequiredString::new("name", |e: &Territory| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
