//! Auth configuration for Currency handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Currency>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CurrencyService;
use crate::domain::entity::Currency;

/// Permission string constants for Currency operations.
pub mod permissions {
    pub const LIST:        &str = "currency:list";
    pub const READ:        &str = "currency:read";
    pub const CREATE:      &str = "currency:create";
    pub const UPDATE:      &str = "currency:update";
    pub const DELETE:      &str = "currency:delete";
    pub const RESTORE:     &str = "currency:restore";
    pub const TRASH:       &str = "currency:trash";
    pub const EMPTY_TRASH: &str = "currency:empty_trash";
    pub const BULK_CREATE: &str = "currency:bulk_create";
    pub const UPSERT:      &str = "currency:upsert";
}

/// Resource policy for Currency — maps CRUD actions to permission strings.
pub struct CurrencyPolicy;

#[async_trait]
impl ResourcePolicy<Currency> for CurrencyPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Currency,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Currency handlers.
///
/// Wraps `CurrencyService` and checks `CurrencyPolicy` before delegating.
pub type CurrencyGuard = PermissionGuard<Currency>;

/// Service-integrated permission guard for Currency (for use in generated handlers).
pub type CurrencyServiceGuard = ServicePermissionGuard<Currency, CurrencyService, CurrencyPolicy>;

// <<< CUSTOM
// END CUSTOM
