//! Auth configuration for CurrencyExchange handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<CurrencyExchange>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CurrencyExchangeService;
use crate::domain::entity::CurrencyExchange;

/// Permission string constants for CurrencyExchange operations.
pub mod permissions {
    pub const LIST:        &str = "currency_exchange:list";
    pub const READ:        &str = "currency_exchange:read";
    pub const CREATE:      &str = "currency_exchange:create";
    pub const UPDATE:      &str = "currency_exchange:update";
    pub const DELETE:      &str = "currency_exchange:delete";
    pub const RESTORE:     &str = "currency_exchange:restore";
    pub const TRASH:       &str = "currency_exchange:trash";
    pub const EMPTY_TRASH: &str = "currency_exchange:empty_trash";
    pub const BULK_CREATE: &str = "currency_exchange:bulk_create";
    pub const UPSERT:      &str = "currency_exchange:upsert";
}

/// Resource policy for CurrencyExchange — maps CRUD actions to permission strings.
pub struct CurrencyExchangePolicy;

#[async_trait]
impl ResourcePolicy<CurrencyExchange> for CurrencyExchangePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &CurrencyExchange,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for CurrencyExchange handlers.
///
/// Wraps `CurrencyExchangeService` and checks `CurrencyExchangePolicy` before delegating.
pub type CurrencyExchangeGuard = PermissionGuard<CurrencyExchange>;

/// Service-integrated permission guard for CurrencyExchange (for use in generated handlers).
pub type CurrencyExchangeServiceGuard = ServicePermissionGuard<CurrencyExchange, CurrencyExchangeService, CurrencyExchangePolicy>;

// <<< CUSTOM
// END CUSTOM
