//! Auth configuration for Incoterm handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Incoterm>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::IncotermService;
use crate::domain::entity::Incoterm;

/// Permission string constants for Incoterm operations.
pub mod permissions {
    pub const LIST:        &str = "incoterm:list";
    pub const READ:        &str = "incoterm:read";
    pub const CREATE:      &str = "incoterm:create";
    pub const UPDATE:      &str = "incoterm:update";
    pub const DELETE:      &str = "incoterm:delete";
    pub const RESTORE:     &str = "incoterm:restore";
    pub const TRASH:       &str = "incoterm:trash";
    pub const EMPTY_TRASH: &str = "incoterm:empty_trash";
    pub const BULK_CREATE: &str = "incoterm:bulk_create";
    pub const UPSERT:      &str = "incoterm:upsert";
}

/// Resource policy for Incoterm — maps CRUD actions to permission strings.
pub struct IncotermPolicy;

#[async_trait]
impl ResourcePolicy<Incoterm> for IncotermPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Incoterm,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Incoterm handlers.
///
/// Wraps `IncotermService` and checks `IncotermPolicy` before delegating.
pub type IncotermGuard = PermissionGuard<Incoterm>;

/// Service-integrated permission guard for Incoterm (for use in generated handlers).
pub type IncotermServiceGuard = ServicePermissionGuard<Incoterm, IncotermService, IncotermPolicy>;

// <<< CUSTOM
// END CUSTOM
