//! Auth configuration for TermsAndConditions handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<TermsAndConditions>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TermsAndConditionsService;
use crate::domain::entity::TermsAndConditions;

/// Permission string constants for TermsAndConditions operations.
pub mod permissions {
    pub const LIST:        &str = "terms_and_conditions:list";
    pub const READ:        &str = "terms_and_conditions:read";
    pub const CREATE:      &str = "terms_and_conditions:create";
    pub const UPDATE:      &str = "terms_and_conditions:update";
    pub const DELETE:      &str = "terms_and_conditions:delete";
    pub const RESTORE:     &str = "terms_and_conditions:restore";
    pub const TRASH:       &str = "terms_and_conditions:trash";
    pub const EMPTY_TRASH: &str = "terms_and_conditions:empty_trash";
    pub const BULK_CREATE: &str = "terms_and_conditions:bulk_create";
    pub const UPSERT:      &str = "terms_and_conditions:upsert";
}

/// Resource policy for TermsAndConditions — maps CRUD actions to permission strings.
pub struct TermsAndConditionsPolicy;

#[async_trait]
impl ResourcePolicy<TermsAndConditions> for TermsAndConditionsPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &TermsAndConditions,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for TermsAndConditions handlers.
///
/// Wraps `TermsAndConditionsService` and checks `TermsAndConditionsPolicy` before delegating.
pub type TermsAndConditionsGuard = PermissionGuard<TermsAndConditions>;

/// Service-integrated permission guard for TermsAndConditions (for use in generated handlers).
pub type TermsAndConditionsServiceGuard = ServicePermissionGuard<TermsAndConditions, TermsAndConditionsService, TermsAndConditionsPolicy>;

// <<< CUSTOM
// END CUSTOM
