//! Auth configuration for Territory handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Territory>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TerritoryService;
use crate::domain::entity::Territory;

/// Permission string constants for Territory operations.
pub mod permissions {
    pub const LIST:        &str = "territory:list";
    pub const READ:        &str = "territory:read";
    pub const CREATE:      &str = "territory:create";
    pub const UPDATE:      &str = "territory:update";
    pub const DELETE:      &str = "territory:delete";
    pub const RESTORE:     &str = "territory:restore";
    pub const TRASH:       &str = "territory:trash";
    pub const EMPTY_TRASH: &str = "territory:empty_trash";
    pub const BULK_CREATE: &str = "territory:bulk_create";
    pub const UPSERT:      &str = "territory:upsert";
}

/// Resource policy for Territory — maps CRUD actions to permission strings.
pub struct TerritoryPolicy;

#[async_trait]
impl ResourcePolicy<Territory> for TerritoryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Territory,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Territory handlers.
///
/// Wraps `TerritoryService` and checks `TerritoryPolicy` before delegating.
pub type TerritoryGuard = PermissionGuard<Territory>;

/// Service-integrated permission guard for Territory (for use in generated handlers).
pub type TerritoryServiceGuard = ServicePermissionGuard<Territory, TerritoryService, TerritoryPolicy>;

// <<< CUSTOM
// END CUSTOM
