//! CurrencyExchange API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the CurrencyExchange CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CURRENCYEXCHANGE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for CurrencyExchange
pub struct CurrencyExchangeTestData;

impl TestDataGenerator for CurrencyExchangeTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": null,
            "from_currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "to_currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "rate": 0,
            "effective_from": Utc::now().format("%Y-%m-%d").to_string(),
            "effective_to": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": null,
            "from_currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "to_currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "rate": 0,
            "effective_from": Utc::now().format("%Y-%m-%d").to_string(),
            "effective_to": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// CURRENCYEXCHANGE API TEST
// ============================================================================

/// CurrencyExchange API test suite
pub struct CurrencyExchangeApiTest {
    inner: GenericCrudTest<CurrencyExchangeTestData>,
}

impl CurrencyExchangeApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/currency_exchanges", "CurrencyExchange");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CurrencyExchangeTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CurrencyExchangeApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_currency_exchange_crud() {
        let mut test = CurrencyExchangeApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add CurrencyExchange specific tests here
// <<< CUSTOM TESTS END >>>
