//! Currency API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Currency CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CURRENCY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Currency
pub struct CurrencyTestData;

impl TestDataGenerator for CurrencyTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "iso_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "symbol": null,
            "decimal_places": 1,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "iso_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "symbol": null,
            "decimal_places": 1,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// CURRENCY API TEST
// ============================================================================

/// Currency API test suite
pub struct CurrencyApiTest {
    inner: GenericCrudTest<CurrencyTestData>,
}

impl CurrencyApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/currencies", "Currency");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CurrencyTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CurrencyApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_currency_crud() {
        let mut test = CurrencyApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Currency specific tests here
// <<< CUSTOM TESTS END >>>
