//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod currency_api_test;
pub mod currency_exchange_api_test;
pub mod incoterm_api_test;
pub mod terms_and_conditions_api_test;
pub mod territory_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use currency_api_test::*;
pub use currency_exchange_api_test::*;
pub use incoterm_api_test::*;
pub use terms_and_conditions_api_test::*;
pub use territory_api_test::*;
