//! Corporate Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::CurrencyService;
use crate::application::service::CurrencyExchangeService;
use crate::application::service::IncotermService;
use crate::application::service::TermsAndConditionsService;
use crate::application::service::TerritoryService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Currency service
    pub currency_service: Arc<CurrencyService>,
    /// CurrencyExchange service
    pub currency_exchange_service: Arc<CurrencyExchangeService>,
    /// Incoterm service
    pub incoterm_service: Arc<IncotermService>,
    /// TermsAndConditions service
    pub terms_and_conditions_service: Arc<TermsAndConditionsService>,
    /// Territory service
    pub territory_service: Arc<TerritoryService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        currency_service: Arc<CurrencyService>,
        currency_exchange_service: Arc<CurrencyExchangeService>,
        incoterm_service: Arc<IncotermService>,
        terms_and_conditions_service: Arc<TermsAndConditionsService>,
        territory_service: Arc<TerritoryService>
    ) -> Self {
        Self {
            currency_service,
            currency_exchange_service,
            incoterm_service,
            terms_and_conditions_service,
            territory_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::CorporateModule) -> Self {
        Self {
            currency_service: module.currency_service.clone(),
            currency_exchange_service: module.currency_exchange_service.clone(),
            incoterm_service: module.incoterm_service.clone(),
            terms_and_conditions_service: module.terms_and_conditions_service.clone(),
            territory_service: module.territory_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    currency_service: Option<Arc<CurrencyService>>,
    currency_exchange_service: Option<Arc<CurrencyExchangeService>>,
    incoterm_service: Option<Arc<IncotermService>>,
    terms_and_conditions_service: Option<Arc<TermsAndConditionsService>>,
    territory_service: Option<Arc<TerritoryService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Currency service.
    pub fn with_currency_service(mut self, service: Arc<CurrencyService>) -> Self {
        self.currency_service = Some(service);
        self
    }

    /// Set the CurrencyExchange service.
    pub fn with_currency_exchange_service(mut self, service: Arc<CurrencyExchangeService>) -> Self {
        self.currency_exchange_service = Some(service);
        self
    }

    /// Set the Incoterm service.
    pub fn with_incoterm_service(mut self, service: Arc<IncotermService>) -> Self {
        self.incoterm_service = Some(service);
        self
    }

    /// Set the TermsAndConditions service.
    pub fn with_terms_and_conditions_service(mut self, service: Arc<TermsAndConditionsService>) -> Self {
        self.terms_and_conditions_service = Some(service);
        self
    }

    /// Set the Territory service.
    pub fn with_territory_service(mut self, service: Arc<TerritoryService>) -> Self {
        self.territory_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            currency_service: self.currency_service.expect("currency_service is required"),
            currency_exchange_service: self.currency_exchange_service.expect("currency_exchange_service is required"),
            incoterm_service: self.incoterm_service.expect("incoterm_service is required"),
            terms_and_conditions_service: self.terms_and_conditions_service.expect("terms_and_conditions_service is required"),
            territory_service: self.territory_service.expect("territory_service is required"),
        }
    }
}
