//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    currency_handler::create_currency_routes,
    currency_exchange_handler::create_currency_exchange_routes,
    incoterm_handler::create_incoterm_routes,
    terms_and_conditions_handler::create_terms_and_conditions_routes,
    territory_handler::create_territory_routes,
};

use crate::application::service::{
    CurrencyService,
    CurrencyExchangeService,
    IncotermService,
    TermsAndConditionsService,
    TerritoryService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub currency: Arc<CurrencyService>,
    pub currency_exchange: Arc<CurrencyExchangeService>,
    pub incoterm: Arc<IncotermService>,
    pub terms_and_conditions: Arc<TermsAndConditionsService>,
    pub territory: Arc<TerritoryService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Currency routes (12 Backbone endpoints)
        .merge(create_currency_routes(services.currency))
        // CurrencyExchange routes (12 Backbone endpoints)
        .merge(create_currency_exchange_routes(services.currency_exchange))
        // Incoterm routes (12 Backbone endpoints)
        .merge(create_incoterm_routes(services.incoterm))
        // TermsAndConditions routes (12 Backbone endpoints)
        .merge(create_terms_and_conditions_routes(services.terms_and_conditions))
        // Territory routes (12 Backbone endpoints)
        .merge(create_territory_routes(services.territory))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn currency_routes(service: Arc<CurrencyService>) -> Router {
        create_currency_routes(service)
    }

    pub fn currency_exchange_routes(service: Arc<CurrencyExchangeService>) -> Router {
        create_currency_exchange_routes(service)
    }

    pub fn incoterm_routes(service: Arc<IncotermService>) -> Router {
        create_incoterm_routes(service)
    }

    pub fn terms_and_conditions_routes(service: Arc<TermsAndConditionsService>) -> Router {
        create_terms_and_conditions_routes(service)
    }

    pub fn territory_routes(service: Arc<TerritoryService>) -> Router {
        create_territory_routes(service)
    }

}
