//! Public events for Corporate module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// CURRENCY EVENTS
// ============================================================================

/// Event published when a Currency is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CurrencyCreatedEvent {
    pub id: CurrencyId,
    pub data: CurrencyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Currency is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CurrencyUpdatedEvent {
    pub id: CurrencyId,
    pub data: CurrencyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Currency is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CurrencyDeletedEvent {
    pub id: CurrencyId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CURRENCYEXCHANGE EVENTS
// ============================================================================

/// Event published when a CurrencyExchange is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CurrencyExchangeCreatedEvent {
    pub id: CurrencyExchangeId,
    pub data: CurrencyExchangeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CurrencyExchange is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CurrencyExchangeUpdatedEvent {
    pub id: CurrencyExchangeId,
    pub data: CurrencyExchangeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CurrencyExchange is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CurrencyExchangeDeletedEvent {
    pub id: CurrencyExchangeId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// INCOTERM EVENTS
// ============================================================================

/// Event published when a Incoterm is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IncotermCreatedEvent {
    pub id: IncotermId,
    pub data: IncotermDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Incoterm is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IncotermUpdatedEvent {
    pub id: IncotermId,
    pub data: IncotermDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Incoterm is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IncotermDeletedEvent {
    pub id: IncotermId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// TERMSANDCONDITIONS EVENTS
// ============================================================================

/// Event published when a TermsAndConditions is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TermsAndConditionsCreatedEvent {
    pub id: TermsAndConditionsId,
    pub data: TermsAndConditionsDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TermsAndConditions is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TermsAndConditionsUpdatedEvent {
    pub id: TermsAndConditionsId,
    pub data: TermsAndConditionsDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TermsAndConditions is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TermsAndConditionsDeletedEvent {
    pub id: TermsAndConditionsId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// TERRITORY EVENTS
// ============================================================================

/// Event published when a Territory is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TerritoryCreatedEvent {
    pub id: TerritoryId,
    pub data: TerritoryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Territory is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TerritoryUpdatedEvent {
    pub id: TerritoryId,
    pub data: TerritoryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Territory is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TerritoryDeletedEvent {
    pub id: TerritoryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Corporate module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CorporateEvent {
    CurrencyCreated(CurrencyCreatedEvent),
    CurrencyUpdated(CurrencyUpdatedEvent),
    CurrencyDeleted(CurrencyDeletedEvent),
    CurrencyExchangeCreated(CurrencyExchangeCreatedEvent),
    CurrencyExchangeUpdated(CurrencyExchangeUpdatedEvent),
    CurrencyExchangeDeleted(CurrencyExchangeDeletedEvent),
    IncotermCreated(IncotermCreatedEvent),
    IncotermUpdated(IncotermUpdatedEvent),
    IncotermDeleted(IncotermDeletedEvent),
    TermsAndConditionsCreated(TermsAndConditionsCreatedEvent),
    TermsAndConditionsUpdated(TermsAndConditionsUpdatedEvent),
    TermsAndConditionsDeleted(TermsAndConditionsDeletedEvent),
    TerritoryCreated(TerritoryCreatedEvent),
    TerritoryUpdated(TerritoryUpdatedEvent),
    TerritoryDeleted(TerritoryDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorporateEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for CorporateEventMetadata {
    fn default() -> Self {
        Self {
            module: "corporate",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
