//! Corporate Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Corporate exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use corporate::exports::{CurrencyDto, CorporateQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `CurrencyDto` - Data transfer object for Currency
/// - `CurrencySummary` - Summary view of Currency
/// - `CurrencyId` - Type-safe ID wrapper
/// - `CurrencyExchangeDto` - Data transfer object for CurrencyExchange
/// - `CurrencyExchangeSummary` - Summary view of CurrencyExchange
/// - `CurrencyExchangeId` - Type-safe ID wrapper
/// - `IncotermDto` - Data transfer object for Incoterm
/// - `IncotermSummary` - Summary view of Incoterm
/// - `IncotermId` - Type-safe ID wrapper
/// - `TermsAndConditionsDto` - Data transfer object for TermsAndConditions
/// - `TermsAndConditionsSummary` - Summary view of TermsAndConditions
/// - `TermsAndConditionsId` - Type-safe ID wrapper
/// - `TerritoryDto` - Data transfer object for Territory
/// - `TerritorySummary` - Summary view of Territory
/// - `TerritoryId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `CorporateQueryService` - Read-only queries
///
/// ## Public Events
/// - `CurrencyCreatedEvent` - Published when Currency is created
/// - `CurrencyUpdatedEvent` - Published when Currency is updated
/// - `CurrencyDeletedEvent` - Published when Currency is deleted
/// - `CurrencyExchangeCreatedEvent` - Published when CurrencyExchange is created
/// - `CurrencyExchangeUpdatedEvent` - Published when CurrencyExchange is updated
/// - `CurrencyExchangeDeletedEvent` - Published when CurrencyExchange is deleted
/// - `IncotermCreatedEvent` - Published when Incoterm is created
/// - `IncotermUpdatedEvent` - Published when Incoterm is updated
/// - `IncotermDeletedEvent` - Published when Incoterm is deleted
/// - `TermsAndConditionsCreatedEvent` - Published when TermsAndConditions is created
/// - `TermsAndConditionsUpdatedEvent` - Published when TermsAndConditions is updated
/// - `TermsAndConditionsDeletedEvent` - Published when TermsAndConditions is deleted
/// - `TerritoryCreatedEvent` - Published when Territory is created
/// - `TerritoryUpdatedEvent` - Published when Territory is updated
/// - `TerritoryDeletedEvent` - Published when Territory is deleted
pub struct ExportSummary;
