//! Public services for Corporate module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.


// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
use super::types::{Converted, RegisterRate, SpotRate};
use crate::application::service::fx_service::NewRate;
use crate::application::service::FxService;
use crate::domain::entity::RateType;
use anyhow::Result;
use async_trait::async_trait;
use chrono::NaiveDate;
use rust_decimal::Decimal;
use std::sync::Arc;
use uuid::Uuid;

/// The published FX contract. Sibling modules program against THIS trait — not
/// `application::service::fx_service` — so the engine's internals are free to
/// change behind a stable surface. Returns `anyhow::Result`; the application's
/// typed `FxError` is mapped to `anyhow::Error` at the boundary (consumers that
/// need to distinguish NoRate etc. should call through the HTTP layer, which
/// maps the typed error to status codes).
#[async_trait]
pub trait CorporateFxPort: Send + Sync {
    /// Convert `amount` from -> to at the rate effective on `on_date`, rounded
    /// to the quote currency's minor-unit precision. Same-currency is identity.
    async fn convert(
        &self,
        company_id: Option<Uuid>,
        amount: Decimal,
        from: &str,
        to: &str,
        on_date: NaiveDate,
    ) -> Result<Converted>;

    /// Read the spot rate in force for a directed pair at (or immediately
    /// before) `on_or_before` — a raw rate read (no amount, no rounding, no
    /// inverse fallback). Refuses when no window covers the date; a company
    /// rate wins over a global one.
    async fn spot_on_or_before(
        &self,
        company_id: Option<Uuid>,
        from: &str,
        to: &str,
        on_or_before: NaiveDate,
    ) -> Result<SpotRate>;

    /// Register a directed, effective-dated rate, rejecting a window that
    /// overlaps an existing one for the same pair + company scope. Returns the
    /// new (or updated) rate row id.
    async fn register_rate(&self, rate: RegisterRate) -> Result<Uuid>;
}

/// Adapter that satisfies [`CorporateFxPort`] by delegating to the hand-authored
/// [`FxService`]. Constructed by `CorporateModule::fx_port()`.
pub struct CorporateFxServiceImpl {
    inner: Arc<FxService>,
}

impl CorporateFxServiceImpl {
    pub fn new(inner: Arc<FxService>) -> Self {
        Self { inner }
    }
}

#[async_trait]
impl CorporateFxPort for CorporateFxServiceImpl {
    async fn convert(
        &self,
        company_id: Option<Uuid>,
        amount: Decimal,
        from: &str,
        to: &str,
        on_date: NaiveDate,
    ) -> Result<Converted> {
        let c = self
            .inner
            .convert(company_id, amount, from, to, on_date)
            .await?;
        Ok(Converted {
            amount: c.amount,
            rate: c.rate,
            rate_id: c.rate_id,
            rate_date: c.rate_date,
            inverse: c.inverse,
        })
    }

    async fn spot_on_or_before(
        &self,
        company_id: Option<Uuid>,
        from: &str,
        to: &str,
        on_or_before: NaiveDate,
    ) -> Result<SpotRate> {
        let s = self
            .inner
            .spot_on_or_before(company_id, from, to, on_or_before)
            .await?;
        Ok(SpotRate {
            rate: s.rate,
            rate_id: s.rate_id,
            effective_from: s.effective_from,
        })
    }

    async fn register_rate(&self, r: RegisterRate) -> Result<Uuid> {
        self.inner
            .upsert_rate(NewRate {
                company_id: r.company_id,
                from_currency: r.from,
                to_currency: r.to,
                rate: r.rate,
                effective_from: r.effective_from,
                effective_to: r.effective_to,
                rate_type: r.rate_type.unwrap_or(RateType::Spot),
                source: r.source,
            })
            .await
            .map_err(Into::into)
    }
}
// <<< CUSTOM SERVICES END >>>
