//! Public services for Corporate module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Corporate module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait CorporateQueryService: Send + Sync {
    /// Get Currency by ID
    async fn get_currency(&self, id: CurrencyId) -> Result<Option<CurrencyDto>>;

    /// Get Currency summary by ID
    async fn get_currency_summary(&self, id: CurrencyId) -> Result<Option<CurrencySummary>>;

    /// Check if Currency exists
    async fn currency_exists(&self, id: CurrencyId) -> Result<bool>;

    /// Get CurrencyExchange by ID
    async fn get_currency_exchange(&self, id: CurrencyExchangeId) -> Result<Option<CurrencyExchangeDto>>;

    /// Get CurrencyExchange summary by ID
    async fn get_currency_exchange_summary(&self, id: CurrencyExchangeId) -> Result<Option<CurrencyExchangeSummary>>;

    /// Check if CurrencyExchange exists
    async fn currency_exchange_exists(&self, id: CurrencyExchangeId) -> Result<bool>;

    /// Get Incoterm by ID
    async fn get_incoterm(&self, id: IncotermId) -> Result<Option<IncotermDto>>;

    /// Get Incoterm summary by ID
    async fn get_incoterm_summary(&self, id: IncotermId) -> Result<Option<IncotermSummary>>;

    /// Check if Incoterm exists
    async fn incoterm_exists(&self, id: IncotermId) -> Result<bool>;

    /// Get TermsAndConditions by ID
    async fn get_terms_and_conditions(&self, id: TermsAndConditionsId) -> Result<Option<TermsAndConditionsDto>>;

    /// Get TermsAndConditions summary by ID
    async fn get_terms_and_conditions_summary(&self, id: TermsAndConditionsId) -> Result<Option<TermsAndConditionsSummary>>;

    /// Check if TermsAndConditions exists
    async fn terms_and_conditions_exists(&self, id: TermsAndConditionsId) -> Result<bool>;

    /// Get Territory by ID
    async fn get_territory(&self, id: TerritoryId) -> Result<Option<TerritoryDto>>;

    /// Get Territory summary by ID
    async fn get_territory_summary(&self, id: TerritoryId) -> Result<Option<TerritorySummary>>;

    /// Check if Territory exists
    async fn territory_exists(&self, id: TerritoryId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of CorporateQueryService
pub struct CorporateQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> CorporateQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
