//! Public types for Corporate module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// CURRENCY TYPES
// ============================================================================

/// Type-safe ID for Currency
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CurrencyId(pub Uuid);

impl CurrencyId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CurrencyId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CurrencyId> for Uuid {
    fn from(id: CurrencyId) -> Self {
        id.0
    }
}

/// Data transfer object for Currency
///
/// This is the public representation of Currency for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CurrencyDto {
    pub id: CurrencyId,
    pub iso_code: String,
    pub name: String,
    pub symbol: Option<String>,
    pub decimal_places: i32,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of Currency for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CurrencySummary {
    pub id: CurrencyId,
    pub name: String,
}

/// Reference to Currency for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CurrencyRef {
    pub id: CurrencyId,
}

// ============================================================================
// CURRENCYEXCHANGE TYPES
// ============================================================================

/// Type-safe ID for CurrencyExchange
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CurrencyExchangeId(pub Uuid);

impl CurrencyExchangeId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CurrencyExchangeId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CurrencyExchangeId> for Uuid {
    fn from(id: CurrencyExchangeId) -> Self {
        id.0
    }
}

/// Data transfer object for CurrencyExchange
///
/// This is the public representation of CurrencyExchange for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CurrencyExchangeDto {
    pub id: CurrencyExchangeId,
    pub company_id: Option<Uuid>,
    pub from_currency: String,
    pub to_currency: String,
    pub rate: Decimal,
    pub effective_from: NaiveDate,
    pub effective_to: Option<NaiveDate>,
    pub metadata: serde_json::Value,
}

/// Summary view of CurrencyExchange for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CurrencyExchangeSummary {
    pub id: CurrencyExchangeId,
}

/// Reference to CurrencyExchange for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CurrencyExchangeRef {
    pub id: CurrencyExchangeId,
}

// ============================================================================
// INCOTERM TYPES
// ============================================================================

/// Type-safe ID for Incoterm
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct IncotermId(pub Uuid);

impl IncotermId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for IncotermId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<IncotermId> for Uuid {
    fn from(id: IncotermId) -> Self {
        id.0
    }
}

/// Data transfer object for Incoterm
///
/// This is the public representation of Incoterm for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IncotermDto {
    pub id: IncotermId,
    pub code: String,
    pub name: String,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of Incoterm for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IncotermSummary {
    pub id: IncotermId,
    pub name: String,
}

/// Reference to Incoterm for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IncotermRef {
    pub id: IncotermId,
}

// ============================================================================
// TERMSANDCONDITIONS TYPES
// ============================================================================

/// Type-safe ID for TermsAndConditions
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TermsAndConditionsId(pub Uuid);

impl TermsAndConditionsId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TermsAndConditionsId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TermsAndConditionsId> for Uuid {
    fn from(id: TermsAndConditionsId) -> Self {
        id.0
    }
}

/// Data transfer object for TermsAndConditions
///
/// This is the public representation of TermsAndConditions for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TermsAndConditionsDto {
    pub id: TermsAndConditionsId,
    pub code: String,
    pub title: String,
    pub body: String,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of TermsAndConditions for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TermsAndConditionsSummary {
    pub id: TermsAndConditionsId,
    pub title: String,
}

/// Reference to TermsAndConditions for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TermsAndConditionsRef {
    pub id: TermsAndConditionsId,
}

// ============================================================================
// TERRITORY TYPES
// ============================================================================

/// Type-safe ID for Territory
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TerritoryId(pub Uuid);

impl TerritoryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TerritoryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TerritoryId> for Uuid {
    fn from(id: TerritoryId) -> Self {
        id.0
    }
}

/// Data transfer object for Territory
///
/// This is the public representation of Territory for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TerritoryDto {
    pub id: TerritoryId,
    pub code: String,
    pub name: String,
    pub parent_id: Option<Uuid>,
    pub is_group: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of Territory for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TerritorySummary {
    pub id: TerritoryId,
    pub name: String,
}

/// Reference to Territory for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TerritoryRef {
    pub id: TerritoryId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
