//! Corporate Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::CurrencyService;
pub use application::service::CurrencyExchangeService;
pub use application::service::IncotermService;
pub use application::service::TermsAndConditionsService;
pub use application::service::TerritoryService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Corporate module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let corporate = CorporateModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = corporate.all_crud_routes();
/// ```
pub struct CorporateModule {
    pub currency_service: Arc<CurrencyService>,
    pub currency_exchange_service: Arc<CurrencyExchangeService>,
    pub incoterm_service: Arc<IncotermService>,
    pub terms_and_conditions_service: Arc<TermsAndConditionsService>,
    pub territory_service: Arc<TerritoryService>,
}

impl CorporateModule {
    /// Create a new module builder
    pub fn builder() -> CorporateModuleBuilder {
        CorporateModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_currency_routes,
            create_currency_exchange_routes,
            create_incoterm_routes,
            create_terms_and_conditions_routes,
            create_territory_routes,
        };

        Router::new()
            .merge(create_currency_routes(self.currency_service.clone()))
            .merge(create_currency_exchange_routes(self.currency_exchange_service.clone()))
            .merge(create_incoterm_routes(self.incoterm_service.clone()))
            .merge(create_terms_and_conditions_routes(self.terms_and_conditions_service.clone()))
            .merge(create_territory_routes(self.territory_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for CorporateModule
pub struct CorporateModuleBuilder {
    db_pool: Option<PgPool>,
}

impl CorporateModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<CorporateModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Currency service
        let currency_repository = Arc::new(CurrencyRepository::new(db_pool.clone()));
        let currency_service = Arc::new(CurrencyService::with_repository(currency_repository.clone()));

        // CurrencyExchange service
        let currency_exchange_repository = Arc::new(CurrencyExchangeRepository::new(db_pool.clone()));
        let currency_exchange_service = Arc::new(CurrencyExchangeService::with_repository(currency_exchange_repository.clone()));

        // Incoterm service
        let incoterm_repository = Arc::new(IncotermRepository::new(db_pool.clone()));
        let incoterm_service = Arc::new(IncotermService::with_repository(incoterm_repository.clone()));

        // TermsAndConditions service
        let terms_and_conditions_repository = Arc::new(TermsAndConditionsRepository::new(db_pool.clone()));
        let terms_and_conditions_service = Arc::new(TermsAndConditionsService::with_repository(terms_and_conditions_repository.clone()));

        // Territory service
        let territory_repository = Arc::new(TerritoryRepository::new(db_pool.clone()));
        let territory_service = Arc::new(TerritoryService::with_repository(territory_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(CorporateModule {
            currency_service,
            currency_exchange_service,
            incoterm_service,
            terms_and_conditions_service,
            territory_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for CorporateModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
