//! Use case type aliases for CurrencyExchange aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCurrencyExchangeDto, UpdateCurrencyExchangeDto};
use crate::application::service::CurrencyExchangeService;
use crate::domain::entity::CurrencyExchange;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCurrencyExchangeUseCase = CreateUseCase<CurrencyExchange, CreateCurrencyExchangeDto, CurrencyExchangeService>;
pub type UpdateCurrencyExchangeUseCase = UpdateUseCase<CurrencyExchange, UpdateCurrencyExchangeDto, CurrencyExchangeService>;
pub type GetCurrencyExchangeUseCase    = GetUseCase<CurrencyExchange, CurrencyExchangeService>;
pub type DeleteCurrencyExchangeUseCase = DeleteUseCase<CurrencyExchange, CurrencyExchangeService>;
pub type ListCurrencyExchangeUseCase   = ListUseCase<CurrencyExchange, CurrencyExchangeService>;

// <<< CUSTOM
// END CUSTOM
