//! Use case type aliases for Currency aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCurrencyDto, UpdateCurrencyDto};
use crate::application::service::CurrencyService;
use crate::domain::entity::Currency;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCurrencyUseCase = CreateUseCase<Currency, CreateCurrencyDto, CurrencyService>;
pub type UpdateCurrencyUseCase = UpdateUseCase<Currency, UpdateCurrencyDto, CurrencyService>;
pub type GetCurrencyUseCase    = GetUseCase<Currency, CurrencyService>;
pub type DeleteCurrencyUseCase = DeleteUseCase<Currency, CurrencyService>;
pub type ListCurrencyUseCase   = ListUseCase<Currency, CurrencyService>;

// <<< CUSTOM
// END CUSTOM
