//! Use case type aliases for Incoterm aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateIncotermDto, UpdateIncotermDto};
use crate::application::service::IncotermService;
use crate::domain::entity::Incoterm;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateIncotermUseCase = CreateUseCase<Incoterm, CreateIncotermDto, IncotermService>;
pub type UpdateIncotermUseCase = UpdateUseCase<Incoterm, UpdateIncotermDto, IncotermService>;
pub type GetIncotermUseCase    = GetUseCase<Incoterm, IncotermService>;
pub type DeleteIncotermUseCase = DeleteUseCase<Incoterm, IncotermService>;
pub type ListIncotermUseCase   = ListUseCase<Incoterm, IncotermService>;

// <<< CUSTOM
// END CUSTOM
