//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod currency_usecases;
pub mod currency_exchange_usecases;
pub mod incoterm_usecases;
pub mod terms_and_conditions_usecases;
pub mod territory_usecases;

pub use currency_usecases::{
    CreateCurrencyUseCase, UpdateCurrencyUseCase, GetCurrencyUseCase,
    DeleteCurrencyUseCase, ListCurrencyUseCase,
};
pub use currency_exchange_usecases::{
    CreateCurrencyExchangeUseCase, UpdateCurrencyExchangeUseCase, GetCurrencyExchangeUseCase,
    DeleteCurrencyExchangeUseCase, ListCurrencyExchangeUseCase,
};
pub use incoterm_usecases::{
    CreateIncotermUseCase, UpdateIncotermUseCase, GetIncotermUseCase,
    DeleteIncotermUseCase, ListIncotermUseCase,
};
pub use terms_and_conditions_usecases::{
    CreateTermsAndConditionsUseCase, UpdateTermsAndConditionsUseCase, GetTermsAndConditionsUseCase,
    DeleteTermsAndConditionsUseCase, ListTermsAndConditionsUseCase,
};
pub use territory_usecases::{
    CreateTerritoryUseCase, UpdateTerritoryUseCase, GetTerritoryUseCase,
    DeleteTerritoryUseCase, ListTerritoryUseCase,
};

// <<< CUSTOM
// END CUSTOM
