//! Use case type aliases for TermsAndConditions aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTermsAndConditionsDto, UpdateTermsAndConditionsDto};
use crate::application::service::TermsAndConditionsService;
use crate::domain::entity::TermsAndConditions;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTermsAndConditionsUseCase = CreateUseCase<TermsAndConditions, CreateTermsAndConditionsDto, TermsAndConditionsService>;
pub type UpdateTermsAndConditionsUseCase = UpdateUseCase<TermsAndConditions, UpdateTermsAndConditionsDto, TermsAndConditionsService>;
pub type GetTermsAndConditionsUseCase    = GetUseCase<TermsAndConditions, TermsAndConditionsService>;
pub type DeleteTermsAndConditionsUseCase = DeleteUseCase<TermsAndConditions, TermsAndConditionsService>;
pub type ListTermsAndConditionsUseCase   = ListUseCase<TermsAndConditions, TermsAndConditionsService>;

// <<< CUSTOM
// END CUSTOM
