//! Use case type aliases for Territory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTerritoryDto, UpdateTerritoryDto};
use crate::application::service::TerritoryService;
use crate::domain::entity::Territory;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTerritoryUseCase = CreateUseCase<Territory, CreateTerritoryDto, TerritoryService>;
pub type UpdateTerritoryUseCase = UpdateUseCase<Territory, UpdateTerritoryDto, TerritoryService>;
pub type GetTerritoryUseCase    = GetUseCase<Territory, TerritoryService>;
pub type DeleteTerritoryUseCase = DeleteUseCase<Territory, TerritoryService>;
pub type ListTerritoryUseCase   = ListUseCase<Territory, TerritoryService>;

// <<< CUSTOM
// END CUSTOM
